# Generated by Django 3.0.2 on 2020-02-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100)),
                ('info_link', models.TextField(blank=True, max_length=100)),
                ('image_link', models.TextField(blank=True, max_length=100)),
                ('date_string', models.TextField(blank=True, max_length=100)),
                ('dates', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('long_position', models.DecimalField(blank=True, decimal_places=3, max_digits=8)),
                ('lat_position', models.DecimalField(blank=True, decimal_places=3, max_digits=8)),
                ('location', models.TextField(blank=True)),
                ('province', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
