# Generated by Django 3.0.2 on 2020-02-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WTDAPI', '0002_auto_20200208_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='info_link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
