# Generated by Django 3.0.2 on 2020-02-05 19:20

import Profile.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, validators=[Profile.validators.validate_characters])),
                ('country', models.CharField(blank=True, max_length=30, validators=[Profile.validators.validate_characters])),
                ('profile_picture', models.ImageField(blank=True, default='profile/avatar.jpg', null=True, upload_to='profile')),
                ('profile_small', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('profile_medium', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('city', models.CharField(blank=True, max_length=30, validators=[Profile.validators.validate_characters])),
                ('province', models.CharField(blank=True, max_length=30, validators=[Profile.validators.validate_characters], verbose_name='provice/state')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Friends'), (1, 'Blocked')], default=1)),
                ('uuid', models.UUIDField(editable=False)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_people', to='Profile.Profile')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_people', to='Profile.Profile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='relationships',
            field=models.ManyToManyField(related_name='related_to', through='Profile.Relationship', to='Profile.Profile'),
        ),
    ]
